In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [117]:
df=pd.read_csv('/content/creditcard.csv')
df

<ipython-input-117-9b4e49130649>:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/creditcard.csv')

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.0,Ownhouse,Self_Emp,Matric,2.0,0.802982,9120.0,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.0,Ownhouse,Self_Emp,Graduate,0.0,0.121876,2600.0,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.0,Ownhouse,Self_Emp,PhD,1.0,0.085113,3042.0,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.0,Ownhouse,Self_Emp,Professional,0.0,0.036050,3300.0,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.0,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,63588.0,7.0,0.0,1.0,0.0,0.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [118]:
# The Function Function Will be Give the Rows ans Columns Of the Data
df.shape

(150002, 18)

In [119]:
# The Columns Function will be Give the Columns of the Dataset
df.columns

Index(['NPA Status', 'RevolvingUtilizationOfUnsecuredLines', 'age', 'Gender',
       'Region', 'MonthlyIncome', 'Rented_OwnHouse', 'Occupation', 'Education',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome.1',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents', 'Good_Bad'],
      dtype='object')

In [120]:
#The Size Function will be give the number of elements in the Data Set
df.size

2700036

In [121]:
#Info Function will be give the information about the Data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150002 entries, 0 to 150001
Data columns (total 18 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   NPA Status                            150000 non-null  float64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  float64
 3   Gender                                150000 non-null  object
 4   Region                                150000 non-null  object
 5   MonthlyIncome                         120269 non-null  float64
 6   Rented_OwnHouse                       150000 non-null  object
 7   Occupation                            150000 non-null  object
 8   Education                             150000 non-null  object
 9   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  float64
 10  DebtRatio                             150000 non-null  float64
 11  MonthlyIncome.1                       120269 non-null  float64
 12  NumberOfOpenCreditLinesAndLoans       150000 non-null  float64
 13  NumberOfTimes90DaysLate               150000 non-null  float64
 14  NumberRealEstateLoansOrLines          150000 non-null  float64
 15  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  float64
 16  NumberOfDependents                    146078 non-null  object
 17  Good_Bad                              150000 non-null  object
dtypes: float64(11), object(7)
memory usage: 20.6+ MB

In [122]:
# The Describe Function will be Give the Stastical Exploration of the Numarical columns
df.describe()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,MonthlyIncome,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse
count,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000
mean,0.066840,6.048438,52.295207,6.670221e+03,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387
std,0.249746,249.755371,14.771866,1.438467e+04,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,3.400000e+03,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,5.400000e+03,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000
75%,0.000000,0.559046,63.000000,8.249000e+03,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000
max,1.000000,50708.000000,109.000000,3.008750e+06,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000

In [123]:
#Head Function Will be Give the First 20 Rows of the Data
df.head(20)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.0,Ownhouse,Self_Emp,Matric,2.0,0.802982,9120.0,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.0,Ownhouse,Self_Emp,Graduate,0.0,0.121876,2600.0,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.0,Ownhouse,Self_Emp,PhD,1.0,0.085113,3042.0,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.0,Ownhouse,Self_Emp,Professional,0.0,0.036050,3300.0,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.0,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,63588.0,7.0,0.0,1.0,0.0,0.0,Good
5,0.0,0.213179,74.0,Female,South,3500.0,Ownhouse,Self_Emp,Graduate,0.0,0.375607,3500.0,3.0,0.0,1.0,0.0,1.0,Good
6,0.0,0.305682,57.0,Female,South,NaN,Ownhouse,Self_Emp,PhD,0.0,5710.000000,NaN,8.0,0.0,3.0,0.0,0.0,Good
7,0.0,0.754464,39.0,Female,South,3500.0,Ownhouse,Self_Emp,Post-Grad,0.0,0.209940,3500.0,8.0,0.0,0.0,0.0,0.0,Good
8,0.0,0.116951,27.0,Female,South,NaN,Ownhouse,Self_Emp,Post-Grad,0.0,46.000000,NaN,2.0,0.0,0.0,0.0,NaN,Good
9,0.0,0.189169,57.0,Female,South,23684.0,Ownhouse,Self_Emp,Graduate,0.0,0.606291,23684.0,9.0,0.0,4.0,0.0,2.0,Good
10,0.0,0.644226,30.0,Male,South,2500.0,Ownhouse,Self_Emp,Post-Grad,0.0,0.309476,2500.0,5.0,0.0,0.0,0.0,0.0,Good
11,0.0,0.018798,51.0,Female,South,6501.0,Ownhouse,Self_Emp,Post-Grad,0.0,0.531529,6501.0,7.0,0.0,2.0,0.0,2.0,Good
12,0.0,0.010352,46.0,Female,South,12454.0,Ownhouse,Self_Emp,Post-Grad,0.0,0.298354,12454.0,13.0,0.0,2.0,0.0,2.0,Good
13,1.0,0.964673,40.0,Female,South,13700.0,Ownhouse,Self_Emp,PhD,3.0,0.382965,13700.0,9.0,3.0,1.0,1.0,2.0,Bad
14,0.0,0.019657,76.0,Female,South,0.0,Ownhouse,Self_Emp,Post-Grad,0.0,477.000000,0.0,6.0,0.0,1.0,0.0,0.0,Good
15,0.0,0.548458,64.0,Male,South,11362.0,Ownhouse,Self_Emp,Post-Grad,0.0,0.209892,11362.0,7.0,0.0,1.0,0.0,2.0,Good
16,0.0,0.061086,78.0,Female,South,NaN,Ownhouse,Self_Emp,Graduate,0.0,2058.000000,NaN,10.0,0.0,2.0,0.0,0.0,Good
17,0.0,0.166284,53.0,Male,South,8800.0,Ownhouse,Self_Emp,Graduate,0.0,0.188274,8800.0,7.0,0.0,0.0,0.0,0.0,Good
18,0.0,0.221813,43.0,Female,South,3280.0,Ownhouse,Self_Emp,Post-Grad,0.0,0.527888,3280.0,7.0,0.0,1.0,0.0,2.0,Good
19,0.0,0.602794,25.0,Female,South,333.0,Ownhouse,Self_Emp,Graduate,0.0,0.065868,333.0,2.0,0.0,0.0,0.0,0.0,Good

In [124]:
#The Tail Function Will be Give the Bottom 20 Rows of the Data
df.tail(20)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149982,0.0,0.021046,37.0,Male,North,2760.0,Rented,Officer2,Professional,0.0,0.250272,2760.0,8.0,0.0,0.0,0.0,3,Good
149983,0.0,0.002485,82.0,Male,North,5000.0,Ownhouse,Non-officer,Professional,0.0,0.000800,5000.0,5.0,0.0,0.0,0.0,0,Good
149984,0.0,0.037548,84.0,Male,North,NaN,Rented,Self_Emp,Professional,0.0,25.000000,NaN,5.0,0.0,0.0,0.0,0,Good
149985,0.0,0.954409,26.0,Male,North,1950.0,Rented,Officer2,Professional,0.0,0.324962,1950.0,4.0,0.0,0.0,0.0,0,Good
149986,0.0,0.168102,49.0,Male,North,5000.0,Ownhouse,Non-officer,Professional,0.0,0.080384,5000.0,16.0,0.0,0.0,0.0,1,Good
149987,0.0,1.000000,28.0,Male,North,3249.0,Ownhouse,Self_Emp,Professional,0.0,0.055692,3249.0,3.0,1.0,0.0,0.0,0,Good
149988,0.0,0.902051,31.0,Male,North,7515.0,Rented,Officer2,Professional,1.0,0.347924,7515.0,10.0,0.0,1.0,0.0,0,Good
149989,0.0,0.013356,62.0,Male,North,9233.0,Rented,Non-officer,Professional,0.0,0.001408,9233.0,4.0,0.0,0.0,0.0,3,Good
149990,0.0,0.055518,46.0,Male,North,4335.0,Rented,Self_Emp,Professional,0.0,0.609779,4335.0,7.0,0.0,1.0,0.0,2,Good
149991,0.0,0.104112,59.0,Male,North,10316.0,Ownhouse,Officer2,Professional,0.0,0.477658,10316.0,10.0,0.0,2.0,0.0,0,Good
149992,0.0,0.871976,50.0,Male,North,NaN,Ownhouse,Non-officer,Professional,0.0,4132.000000,NaN,11.0,0.0,1.0,0.0,3,Good
149993,0.0,1.000000,22.0,Male,North,820.0,Ownhouse,Self_Emp,Professional,0.0,0.000000,820.0,1.0,0.0,0.0,0.0,0,Good
149994,0.0,0.385742,50.0,Male,North,3400.0,Rented,Officer2,Professional,0.0,0.404293,3400.0,7.0,0.0,0.0,0.0,0,Good
149995,0.0,0.040674,74.0,Male,North,2100.0,Ownhouse,Non-officer,Professional,0.0,0.225131,2100.0,4.0,0.0,1.0,0.0,0,Good
149996,0.0,0.299745,44.0,Male,North,5584.0,Ownhouse,Self_Emp,Professional,0.0,0.716562,5584.0,4.0,0.0,1.0,0.0,2,Good
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [125]:
# The sample Function will be Give the Random Rows in The Dataset
df.sample(20)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
8560,1.0,0.000000,45.0,Male,South,4000.0,Ownhouse,Self_Emp,Matric,0.0,0.733067,4000.0,11.0,0.0,3.0,0.0,0.0,Bad
39880,0.0,0.120786,82.0,Female,North,NaN,Ownhouse,Officer1,Post-Grad,0.0,181.000000,NaN,4.0,0.0,0.0,0.0,0.0,Good
35648,0.0,0.213833,63.0,Female,North,NaN,Ownhouse,Self_Emp,Matric,0.0,1360.000000,NaN,11.0,0.0,2.0,0.0,0.0,Good
87426,1.0,0.755408,45.0,Male,North,5400.0,Rented,Non-officer,Graduate,0.0,0.092575,5400.0,3.0,4.0,0.0,6.0,1.0,Bad
137235,0.0,0.028658,46.0,Male,West,3750.0,Ownhouse,Officer2,Professional,0.0,0.177553,3750.0,8.0,0.0,2.0,0.0,0,Good
20858,0.0,0.072569,71.0,Female,North,8666.0,Rented,Officer3,Post-Grad,0.0,0.593169,8666.0,21.0,0.0,3.0,0.0,0.0,Good
60591,0.0,0.669170,48.0,Male,Central,13000.0,Rented,Non-officer,Professional,0.0,0.572879,13000.0,9.0,0.0,4.0,0.0,0.0,Good
92836,0.0,0.000000,30.0,Male,Central,1849.0,Rented,Self_Emp,Graduate,1.0,0.203243,1849.0,2.0,0.0,0.0,0.0,0.0,Good
63250,1.0,0.430924,36.0,Female,West,NaN,Ownhouse,Self_Emp,PhD,0.0,4075.000000,NaN,19.0,0.0,2.0,0.0,0.0,Bad
14115,0.0,0.246551,43.0,Female,North,10390.0,Ownhouse,Officer1,Post-Grad,0.0,0.349822,10390.0,8.0,0.0,1.0,0.0,3.0,Good
97494,1.0,1.000000,50.0,Male,North,3879.0,Rented,Non-officer,Graduate,0.0,0.111340,3879.0,1.0,1.0,1.0,0.0,0.0,Bad
23625,0.0,0.028571,46.0,Male,North,7500.0,Rented,Non-officer,Graduate,0.0,0.349287,7500.0,6.0,0.0,1.0,0.0,2.0,Good
5963,0.0,0.012985,62.0,Male,South,NaN,Ownhouse,Self_Emp,Matric,0.0,568.000000,NaN,13.0,0.0,0.0,0.0,0.0,Good
142284,0.0,0.000318,49.0,Male,West,4200.0,Ownhouse,Officer2,Professional,1.0,0.439181,4200.0,11.0,0.0,2.0,0.0,2,Good
42317,0.0,0.132422,52.0,Male,North,8500.0,Ownhouse,Officer1,Post-Grad,0.0,0.397483,8500.0,10.0,0.0,1.0,0.0,3.0,Good
76654,0.0,0.123496,59.0,Female,Central,NaN,Rented,Self_Emp,Professional,0.0,1433.000000,NaN,14.0,0.0,1.0,0.0,0.0,Good
46369,0.0,0.263142,60.0,Female,East,8709.0,Rented,Officer3,Post-Grad,0.0,0.242824,8709.0,11.0,0.0,1.0,0.0,0.0,Good
54864,0.0,0.200309,51.0,Male,East,NaN,Ownhouse,Officer3,Professional,0.0,1873.000000,NaN,4.0,0.0,2.0,0.0,0.0,Good
53774,0.0,0.073151,45.0,Male,East,NaN,Rented,Officer3,Professional,0.0,1715.000000,NaN,4.0,0.0,1.0,0.0,0.0,Good
32808,0.0,0.052900,40.0,Female,North,3336.0,Ownhouse,Non-officer,Graduate,0.0,0.292478,3336.0,5.0,0.0,0.0,0.0,1.0,Good

In [126]:
#drop duplicates Function will be Drop the Duplicate rows in the data set
df=df.drop_duplicates()
df

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.0,Ownhouse,Self_Emp,Matric,2.0,0.802982,9120.0,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.0,Ownhouse,Self_Emp,Graduate,0.0,0.121876,2600.0,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.0,Ownhouse,Self_Emp,PhD,1.0,0.085113,3042.0,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.0,Ownhouse,Self_Emp,Professional,0.0,0.036050,3300.0,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.0,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,63588.0,7.0,0.0,1.0,0.0,0.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [127]:
df.isnull().sum()

NPA Status                                  2
RevolvingUtilizationOfUnsecuredLines        2
age                                         2
Gender                                      2
Region                                      2
MonthlyIncome                           29717
Rented_OwnHouse                             2
Occupation                                  2
Education                                   2
NumberOfTime30-59DaysPastDueNotWorse        2
DebtRatio                                   2
MonthlyIncome.1                         29717
NumberOfOpenCreditLinesAndLoans             2
NumberOfTimes90DaysLate                     2
NumberRealEstateLoansOrLines                2
NumberOfTime60-89DaysPastDueNotWorse        2
NumberOfDependents                       3923
Good_Bad                                    2
dtype: int64

In [128]:
# drop function will be Drop the Coloumns Mention to the Axis=1 -> is Columns axis=0 -> Rows
df=df.drop('MonthlyIncome.1',axis=1)
df

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.0,Ownhouse,Self_Emp,Matric,2.0,0.802982,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.0,Ownhouse,Self_Emp,Graduate,0.0,0.121876,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.0,Ownhouse,Self_Emp,PhD,1.0,0.085113,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.0,Ownhouse,Self_Emp,Professional,0.0,0.036050,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.0,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,7.0,0.0,1.0,0.0,0.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [129]:
# After removing the Columns information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149982 entries, 0 to 150001
Data columns (total 17 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   NPA Status                            149980 non-null  float64
 1   RevolvingUtilizationOfUnsecuredLines  149980 non-null  float64
 2   age                                   149980 non-null  float64
 3   Gender                                149980 non-null  object
 4   Region                                149980 non-null  object
 5   MonthlyIncome                         120265 non-null  float64
 6   Rented_OwnHouse                       149980 non-null  object
 7   Occupation                            149980 non-null  object
 8   Education                             149980 non-null  object
 9   NumberOfTime30-59DaysPastDueNotWorse  149980 non-null  float64
 10  DebtRatio                             149980 non-null  float64
 11  NumberOfOpenCreditLinesAndLoans       149980 non-null  float64
 12  NumberOfTimes90DaysLate               149980 non-null  float64
 13  NumberRealEstateLoansOrLines          149980 non-null  float64
 14  NumberOfTime60-89DaysPastDueNotWorse  149980 non-null  float64
 15  NumberOfDependents                    146059 non-null  object
 16  Good_Bad                              149980 non-null  object
dtypes: float64(10), object(7)
memory usage: 20.6+ MB

In [130]:
df.isnull().sum()

NPA Status                                  2
RevolvingUtilizationOfUnsecuredLines        2
age                                         2
Gender                                      2
Region                                      2
MonthlyIncome                           29717
Rented_OwnHouse                             2
Occupation                                  2
Education                                   2
NumberOfTime30-59DaysPastDueNotWorse        2
DebtRatio                                   2
NumberOfOpenCreditLinesAndLoans             2
NumberOfTimes90DaysLate                     2
NumberRealEstateLoansOrLines                2
NumberOfTime60-89DaysPastDueNotWorse        2
NumberOfDependents                       3923
Good_Bad                                    2
dtype: int64

In [131]:
# Drops the Enter Row when single Column is null Value
df.dropna(subset='Gender',inplace=  True,axis=0)

In [132]:
df.isnull().sum()

NPA Status                                  0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
Gender                                      0
Region                                      0
MonthlyIncome                           29715
Rented_OwnHouse                             0
Occupation                                  0
Education                                   0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3923
Good_Bad                                    0
dtype: int64

In [140]:
# MonthlyIncome Mean
df['MonthlyIncome'].mean()

np.float64(6670.4211366565505)

In [133]:
#null Values Are Fill The MonthlyIncome mean
df['MonthlyIncome']=df['MonthlyIncome'].fillna(df['MonthlyIncome'].mean())

In [141]:
df

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.000000,Ownhouse,Self_Emp,Matric,2.0,0.802982,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.000000,Ownhouse,Self_Emp,Graduate,0.0,0.121876,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.000000,Ownhouse,Self_Emp,PhD,1.0,0.085113,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.000000,Ownhouse,Self_Emp,Professional,0.0,0.036050,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.000000,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,7.0,0.0,1.0,0.0,0.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,0.0,0.040674,74.0,Male,North,2100.000000,Ownhouse,Non-officer,Professional,0.0,0.225131,4.0,0.0,1.0,0.0,0,Good
149996,0.0,0.299745,44.0,Male,North,5584.000000,Ownhouse,Self_Emp,Professional,0.0,0.716562,4.0,0.0,1.0,0.0,2,Good
149997,0.0,0.246044,58.0,Male,North,6670.421137,Rented,Officer2,Professional,0.0,3870.000000,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.000000,Rented,Non-officer,Professional,0.0,0.000000,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.000000,Ownhouse,Self_Emp,Professional,0.0,0.249908,8.0,0.0,2.0,0.0,0,Good

In [142]:
# NumberofDepents Finding the Mode
df['NumberOfDependents'].mode()[0]

0.0

In [138]:
#NumberofDepents null values are Filling to the Mode Function
df['NumberOfDependents']=df['NumberOfDependents'].fillna(df['NumberOfDependents'].mode()[0])

In [139]:
#Cross Check of the Null Values
df.isnull().sum()

NPA Status                              0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
Gender                                  0
Region                                  0
MonthlyIncome                           0
Rented_OwnHouse                         0
Occupation                              0
Education                               0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
Good_Bad                                0
dtype: int64

##**Cross checking the data There is any Null Values**

In [143]:
df.head(20)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.000000,Ownhouse,Self_Emp,Matric,2.0,0.802982,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.000000,Ownhouse,Self_Emp,Graduate,0.0,0.121876,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.000000,Ownhouse,Self_Emp,PhD,1.0,0.085113,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.000000,Ownhouse,Self_Emp,Professional,0.0,0.036050,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.000000,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,7.0,0.0,1.0,0.0,0.0,Good
5,0.0,0.213179,74.0,Female,South,3500.000000,Ownhouse,Self_Emp,Graduate,0.0,0.375607,3.0,0.0,1.0,0.0,1.0,Good
6,0.0,0.305682,57.0,Female,South,6670.421137,Ownhouse,Self_Emp,PhD,0.0,5710.000000,8.0,0.0,3.0,0.0,0.0,Good
7,0.0,0.754464,39.0,Female,South,3500.000000,Ownhouse,Self_Emp,Post-Grad,0.0,0.209940,8.0,0.0,0.0,0.0,0.0,Good
8,0.0,0.116951,27.0,Female,South,6670.421137,Ownhouse,Self_Emp,Post-Grad,0.0,46.000000,2.0,0.0,0.0,0.0,0.0,Good
9,0.0,0.189169,57.0,Female,South,23684.000000,Ownhouse,Self_Emp,Graduate,0.0,0.606291,9.0,0.0,4.0,0.0,2.0,Good
10,0.0,0.644226,30.0,Male,South,2500.000000,Ownhouse,Self_Emp,Post-Grad,0.0,0.309476,5.0,0.0,0.0,0.0,0.0,Good
11,0.0,0.018798,51.0,Female,South,6501.000000,Ownhouse,Self_Emp,Post-Grad,0.0,0.531529,7.0,0.0,2.0,0.0,2.0,Good
12,0.0,0.010352,46.0,Female,South,12454.000000,Ownhouse,Self_Emp,Post-Grad,0.0,0.298354,13.0,0.0,2.0,0.0,2.0,Good
13,1.0,0.964673,40.0,Female,South,13700.000000,Ownhouse,Self_Emp,PhD,3.0,0.382965,9.0,3.0,1.0,1.0,2.0,Bad
14,0.0,0.019657,76.0,Female,South,0.000000,Ownhouse,Self_Emp,Post-Grad,0.0,477.000000,6.0,0.0,1.0,0.0,0.0,Good
15,0.0,0.548458,64.0,Male,South,11362.000000,Ownhouse,Self_Emp,Post-Grad,0.0,0.209892,7.0,0.0,1.0,0.0,2.0,Good
16,0.0,0.061086,78.0,Female,South,6670.421137,Ownhouse,Self_Emp,Graduate,0.0,2058.000000,10.0,0.0,2.0,0.0,0.0,Good
17,0.0,0.166284,53.0,Male,South,8800.000000,Ownhouse,Self_Emp,Graduate,0.0,0.188274,7.0,0.0,0.0,0.0,0.0,Good
18,0.0,0.221813,43.0,Female,South,3280.000000,Ownhouse,Self_Emp,Post-Grad,0.0,0.527888,7.0,0.0,1.0,0.0,2.0,Good
19,0.0,0.602794,25.0,Female,South,333.000000,Ownhouse,Self_Emp,Graduate,0.0,0.065868,2.0,0.0,0.0,0.0,0.0,Good

In [144]:
df.tail(20)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149980,0.0,0.067644,64.0,Male,North,5525.000000,Ownhouse,Non-officer,Professional,0.0,0.254976,12.0,0.0,1.0,0.0,0,Good
149981,0.0,0.810012,43.0,Male,North,6849.000000,Ownhouse,Self_Emp,Professional,0.0,0.121752,4.0,0.0,0.0,0.0,4,Good
149982,0.0,0.021046,37.0,Male,North,2760.000000,Rented,Officer2,Professional,0.0,0.250272,8.0,0.0,0.0,0.0,3,Good
149983,0.0,0.002485,82.0,Male,North,5000.000000,Ownhouse,Non-officer,Professional,0.0,0.000800,5.0,0.0,0.0,0.0,0,Good
149984,0.0,0.037548,84.0,Male,North,6670.421137,Rented,Self_Emp,Professional,0.0,25.000000,5.0,0.0,0.0,0.0,0,Good
149985,0.0,0.954409,26.0,Male,North,1950.000000,Rented,Officer2,Professional,0.0,0.324962,4.0,0.0,0.0,0.0,0,Good
149986,0.0,0.168102,49.0,Male,North,5000.000000,Ownhouse,Non-officer,Professional,0.0,0.080384,16.0,0.0,0.0,0.0,1,Good
149987,0.0,1.000000,28.0,Male,North,3249.000000,Ownhouse,Self_Emp,Professional,0.0,0.055692,3.0,1.0,0.0,0.0,0,Good
149988,0.0,0.902051,31.0,Male,North,7515.000000,Rented,Officer2,Professional,1.0,0.347924,10.0,0.0,1.0,0.0,0,Good
149989,0.0,0.013356,62.0,Male,North,9233.000000,Rented,Non-officer,Professional,0.0,0.001408,4.0,0.0,0.0,0.0,3,Good
149990,0.0,0.055518,46.0,Male,North,4335.000000,Rented,Self_Emp,Professional,0.0,0.609779,7.0,0.0,1.0,0.0,2,Good
149991,0.0,0.104112,59.0,Male,North,10316.000000,Ownhouse,Officer2,Professional,0.0,0.477658,10.0,0.0,2.0,0.0,0,Good
149992,0.0,0.871976,50.0,Male,North,6670.421137,Ownhouse,Non-officer,Professional,0.0,4132.000000,11.0,0.0,1.0,0.0,3,Good
149993,0.0,1.000000,22.0,Male,North,820.000000,Ownhouse,Self_Emp,Professional,0.0,0.000000,1.0,0.0,0.0,0.0,0,Good
149994,0.0,0.385742,50.0,Male,North,3400.000000,Rented,Officer2,Professional,0.0,0.404293,7.0,0.0,0.0,0.0,0,Good
149995,0.0,0.040674,74.0,Male,North,2100.000000,Ownhouse,Non-officer,Professional,0.0,0.225131,4.0,0.0,1.0,0.0,0,Good
149996,0.0,0.299745,44.0,Male,North,5584.000000,Ownhouse,Self_Emp,Professional,0.0,0.716562,4.0,0.0,1.0,0.0,2,Good
149997,0.0,0.246044,58.0,Male,North,6670.421137,Rented,Officer2,Professional,0.0,3870.000000,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.000000,Rented,Non-officer,Professional,0.0,0.000000,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.000000,Ownhouse,Self_Emp,Professional,0.0,0.249908,8.0,0.0,2.0,0.0,0,Good

In [146]:
df.sample(20)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
84038,0.0,0.499229,58.0,Male,Central,17808.000000,Ownhouse,Self_Emp,Professional,0.0,0.431973,11.0,0.0,1.0,0.0,1.0,Good
94616,0.0,0.737660,42.0,Female,Central,10500.000000,Rented,Non-officer,Graduate,0.0,0.552804,9.0,0.0,1.0,0.0,2.0,Good
66509,0.0,1.000000,41.0,Male,Central,14000.000000,Ownhouse,Self_Emp,Professional,0.0,0.206914,7.0,0.0,1.0,0.0,2.0,Good
116196,0.0,0.000000,87.0,Male,West,3500.000000,Rented,Non-officer,Graduate,0.0,0.094830,4.0,0.0,1.0,0.0,0.0,Good
33561,0.0,0.654901,31.0,Male,North,2200.000000,Ownhouse,Self_Emp,PhD,0.0,0.090868,2.0,0.0,0.0,0.0,0.0,Good
63964,0.0,0.018830,56.0,Male,Central,8000.000000,Rented,Non-officer,Professional,0.0,0.079615,10.0,0.0,1.0,0.0,0.0,Good
112148,0.0,0.462917,60.0,Female,South,1.000000,Ownhouse,Self_Emp,Post-Grad,0.0,433.500000,9.0,0.0,0.0,0.0,0.0,Good
50017,0.0,0.599061,57.0,Female,East,2339.000000,Rented,Officer3,Post-Grad,0.0,0.400427,4.0,0.0,0.0,0.0,1.0,Good
110710,0.0,0.000000,44.0,Male,South,6670.421137,Ownhouse,Self_Emp,Matric,0.0,1816.000000,10.0,0.0,2.0,0.0,0.0,Good
22094,0.0,0.173026,33.0,Male,North,5500.000000,Ownhouse,Non-officer,Graduate,0.0,0.285221,7.0,0.0,2.0,0.0,0.0,Good
2410,0.0,0.910789,44.0,Female,South,10000.000000,Ownhouse,Self_Emp,PhD,1.0,0.456254,9.0,1.0,3.0,0.0,2.0,Good
95658,0.0,0.825834,44.0,Female,Central,3370.000000,Ownhouse,Non-officer,Graduate,0.0,0.315040,3.0,0.0,1.0,0.0,0.0,Good
63517,0.0,0.045421,69.0,Male,Central,10000.000000,Rented,Officer2,Professional,0.0,0.124588,11.0,0.0,2.0,0.0,0.0,Good
61593,0.0,0.224296,24.0,Male,Central,2916.000000,Rented,Non-officer,Professional,0.0,0.013713,4.0,0.0,0.0,0.0,0.0,Good
121189,0.0,0.073528,45.0,Male,West,7041.000000,Rented,Non-officer,Graduate,0.0,0.203493,3.0,0.0,1.0,0.0,3.0,Good
29155,0.0,0.115048,62.0,Male,North,3900.000000,Ownhouse,Non-officer,Graduate,0.0,0.134581,12.0,0.0,0.0,0.0,3.0,Good
71462,0.0,0.091781,56.0,Male,Central,8333.000000,Rented,Non-officer,Professional,0.0,0.166787,7.0,0.0,2.0,0.0,0.0,Good
121773,0.0,0.032990,42.0,Female,East,2080.000000,Rented,Officer3,Post-Grad,0.0,0.024507,6.0,0.0,0.0,0.0,2.0,Good
85056,0.0,1.000000,27.0,Male,Central,6670.421137,Ownhouse,Self_Emp,Graduate,0.0,13.000000,0.0,1.0,0.0,0.0,0.0,Good
95624,0.0,0.016934,76.0,Female,Central,4583.000000,Rented,Non-officer,Graduate,0.0,0.048866,8.0,0.0,0.0,0.0,0.0,Good